package com.bank.model;

public enum UserType {

	CLERK,
	CASHIER,
	HEAD_CASHIER,
	ASSISTANT_MANAGER,
	MANAGER,
	SENIOR_MANAGER,
	BRANCH_MANAGER,
	CHIEF_MANAGER,
	ASSISTANT_GENERAL_MANAGER,
	CHAIRMAN,
	MANAGAING_DIRECTOR;
}
